# Generated by Django 2.1.15 on 2020-01-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_auto_20200113_1830"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(max_length=150, null=True, upload_to="userimages"),
        ),
    ]
