# Generated by Django 2.1.15 on 2020-04-03 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200217_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaccountextra',
            name='socialaccount',
        ),
        migrations.DeleteModel(
            name='SocialAccountExtra',
        ),
    ]
