# Generated by Django 2.1.15 on 2020-04-21 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_smsverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smsverification',
            name='type',
            field=models.CharField(choices=[('NA', 'New Account Activation'), ('RP', 'Reset Password'), ('NP', 'New Phone Number'), ('OP', 'Old Phone Number')], default='NA', max_length=2, verbose_name='Type of the SMS Verification'),
        ),
    ]
