# Generated by Django 2.1.15 on 2020-04-21 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200421_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
