site_name: tumar
site_description: A RESTful Django backend system for monitoring multiple GPS trackers.
repo_url: https://github.com/r0ckfella/tumar-backend
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/r0ckfella">r0ckfella</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
