# Generated by Django 2.1.15 on 2019-12-25 11:54

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0004_auto_20191218_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of the event')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed?')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type of machinery')),
                ('machinery_code', models.CharField(max_length=50, verbose_name='Identification code of the machinery')),
            ],
            options={
                'verbose_name': 'Machinery',
                'verbose_name_plural': 'Machinery',
            },
        ),
        migrations.RemoveField(
            model_name='animal',
            name='cow_code',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='cadastre_num',
        ),
        migrations.AddField(
            model_name='animal',
            name='battery_charge',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Battery charge'),
        ),
        migrations.AddField(
            model_name='animal',
            name='imsi',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='IMSI number'),
        ),
        migrations.AddField(
            model_name='animal',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Animal name'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tag_number',
            field=models.CharField(max_length=25, null=True, unique=True, verbose_name='Animal tag number'),
        ),
        migrations.AddField(
            model_name='animal',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='breeding_stock',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Breeding stock'),
        ),
        migrations.AddField(
            model_name='farm',
            name='cadastre_land',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=3857, verbose_name='Personal land'),
        ),
        migrations.AddField(
            model_name='farm',
            name='cadastres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message='Only digits are allowed for the cadastre number. Up to 25 digits allowed.', regex='^\\d+$')]), blank=True, null=True, size=None, verbose_name='Cadastres of the farm'),
        ),
        migrations.AddField(
            model_name='farm',
            name='calves_number',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Number of calves'),
        ),
        migrations.AddField(
            model_name='farm',
            name='requisites',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Requisites'),
        ),
        migrations.AddField(
            model_name='farm',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='animal',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='animals.Farm', verbose_name='Farm'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='legal_person',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Legal person'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geolocations', to='animals.Animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(srid=3857, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='time',
            field=models.DateTimeField(verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machinery', to='animals.Farm', verbose_name='Machinery'),
        ),
        migrations.AddField(
            model_name='event',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='animals.Animal', verbose_name='Animal'),
        ),
    ]
