# Generated by Django 2.1.15 on 2019-12-25 17:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_auto_20191225_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='cadastre_land',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=3857, verbose_name='Personal land'),
        ),
    ]
