# Generated by Django 2.1.15 on 2020-03-03 11:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0012_auto_20200217_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingBulls',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_number', models.CharField(max_length=25, null=True, unique=True, verbose_name='Animal tag number')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Animal name')),
                ('birth_date', models.DateField(null=True, verbose_name='Date of birth')),
                ('image', models.ImageField(blank=True, max_length=150, null=True, upload_to='animalimages', verbose_name='Photo of the animal')),
                ('birth_place', models.CharField(blank=True, max_length=100, verbose_name='Birth Place')),
                ('breed', models.CharField(choices=[('KL', 'Казахская белоголовая'), ('GF', 'Герефорд'), ('AG', 'Ангус'), ('KM', 'Калмыцкая'), ('AK', 'Аулиекольская'), ('SM', 'Симментал'), ('MB', 'Молочные породы'), ('NB', 'Беспородная'), ('CR', 'Кросс'), ('OT', 'Другое')], default='NB', max_length=2, verbose_name='Breed of the animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Farm', verbose_name='Farm')),
            ],
            options={
                'verbose_name': 'Breeding Bull',
                'verbose_name_plural': 'Breeding Bulls',
            },
        ),
        migrations.CreateModel(
            name='BreedingStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_number', models.CharField(max_length=25, null=True, unique=True, verbose_name='Animal tag number')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Animal name')),
                ('birth_date', models.DateField(null=True, verbose_name='Date of birth')),
                ('image', models.ImageField(blank=True, max_length=150, null=True, upload_to='animalimages', verbose_name='Photo of the animal')),
                ('breed', models.CharField(choices=[('KL', 'Казахская белоголовая'), ('GF', 'Герефорд'), ('AG', 'Ангус'), ('KM', 'Калмыцкая'), ('AK', 'Аулиекольская'), ('SM', 'Симментал'), ('MB', 'Молочные породы'), ('NB', 'Беспородная'), ('CR', 'Кросс'), ('OT', 'Другое')], default='NB', max_length=2, verbose_name='Breed of the animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Farm', verbose_name='Farm')),
            ],
            options={
                'verbose_name': 'Breeding Stock',
                'verbose_name_plural': 'Breeding Stock',
            },
        ),
        migrations.CreateModel(
            name='Calf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_number', models.CharField(max_length=25, null=True, unique=True, verbose_name='Animal tag number')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Animal name')),
                ('birth_date', models.DateField(null=True, verbose_name='Date of birth')),
                ('image', models.ImageField(blank=True, max_length=150, null=True, upload_to='animalimages', verbose_name='Photo of the animal')),
                ('wean_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of weaning')),
                ('gender', models.CharField(choices=[('ML', 'Male'), ('FM', 'Female')], default='FM', max_length=2, verbose_name='Gender')),
                ('breed', models.CharField(choices=[('KL', 'Казахская белоголовая'), ('GF', 'Герефорд'), ('AG', 'Ангус'), ('KM', 'Калмыцкая'), ('AK', 'Аулиекольская'), ('SM', 'Симментал'), ('MB', 'Молочные породы'), ('NB', 'Беспородная'), ('CR', 'Кросс'), ('OT', 'Другое')], default='NB', max_length=2, verbose_name='Breed of the animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Farm', verbose_name='Farm')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calves', to='animals.BreedingStock', verbose_name='Mother')),
            ],
            options={
                'verbose_name': 'Calf',
                'verbose_name_plural': 'Calves',
            },
        ),
        migrations.CreateModel(
            name='StoreCattle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_number', models.CharField(max_length=25, null=True, unique=True, verbose_name='Animal tag number')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Animal name')),
                ('birth_date', models.DateField(null=True, verbose_name='Date of birth')),
                ('image', models.ImageField(blank=True, max_length=150, null=True, upload_to='animalimages', verbose_name='Photo of the animal')),
                ('wean_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of weaning')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Farm', verbose_name='Farm')),
            ],
            options={
                'verbose_name': 'Store Cattle',
                'verbose_name_plural': 'Store Cattle',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Farm', verbose_name='Farm'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='animalimages', verbose_name='Photo of the animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='imei',
            field=models.CharField(blank=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Imei must be entered in the format: '123456789012345'. Up to 15 digits allowed.", regex='^\\d{15}$')], verbose_name='IMEI of the tracker'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last updated'),
        ),
    ]
