# Generated by Django 2.1.15 on 2020-03-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0013_auto_20200303_1724"),
    ]

    operations = [
        migrations.RenameModel(old_name="BreedingBulls", new_name="BreedingBull",),
    ]
