# Generated by Django 2.1.15 on 2020-03-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0014_auto_20200303_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='animal',
        ),
        migrations.AlterField(
            model_name='calf',
            name='gender',
            field=models.CharField(choices=[('ML', 'Бычок'), ('FM', 'Телочка')], default='FM', max_length=2, verbose_name='Gender'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
