# Generated by Django 2.1.15 on 2020-03-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0015_auto_20200311_1943"),
    ]

    operations = [
        migrations.AddField(
            model_name="calf",
            name="Active",
            field=models.BooleanField(default=True, verbose_name="Active?"),
        ),
    ]
