# Generated by Django 2.1.15 on 2020-05-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0018_auto_20200319_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='battery_charge',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Battery charge'),
        ),
    ]
