# Generated by Django 2.1.15 on 2020-05-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0019_auto_20200509_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calf',
            old_name='Active',
            new_name='active',
        ),
    ]
