# Generated by Django 2.1.15 on 2020-05-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0020_auto_20200511_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calf',
            name='wean_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of weaning'),
        ),
    ]
