# Generated by Django 2.2.12 on 2020-05-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
