# Generated by Django 2.1.15 on 2020-02-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageryrequest',
            options={'verbose_name': 'Imagery Request', 'verbose_name_plural': 'Imagery Requests'},
        ),
    ]
