# Generated by Django 2.1.15 on 2020-04-03 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_auto_20200219_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageryrequest',
            name='cadastre',
        ),
        migrations.RemoveField(
            model_name='imageryrequest',
            name='farm',
        ),
        migrations.DeleteModel(
            name='ImageryRequest',
        ),
    ]
