# Generated by Django 2.2.12 on 2020-05-18 23:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0021_auto_20200511_1929'),
        ('indicators', '0003_auto_20200403_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageryRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndvi', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('gndvi', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('clgreen', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('ndmi', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('ndsi', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Request creation date')),
                ('requested_date', models.DateField(default=django.utils.timezone.now, verbose_name='Request scheduled time')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Request finish time')),
                ('results_dir', models.CharField(blank=True, max_length=120, null=True)),
                ('ndvi_dir', models.CharField(blank=True, max_length=120, null=True)),
                ('gndvi_dir', models.CharField(blank=True, max_length=120, null=True)),
                ('clgreen_dir', models.CharField(blank=True, max_length=120, null=True)),
                ('ndmi_dir', models.CharField(blank=True, max_length=120, null=True)),
                ('rgb_dir', models.CharField(blank=True, max_length=120, null=True)),
                ('is_layer_created', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('WA', 'Waiting for new imagery'), ('PR', 'Processing'), ('FI', 'Finished'), ('FA', 'Failed'), ('FE', 'Free requests expired')], default='PE', max_length=2, verbose_name='Status')),
                ('cadastre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagery_requests', to='animals.Cadastre', verbose_name='Cadastre')),
            ],
            options={
                'verbose_name': 'Imagery Request',
                'verbose_name_plural': 'Imagery Requests',
            },
        ),
    ]
