# Generated by Django 2.2.12 on 2020-05-19 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20200404_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='community.Post', verbose_name='Post'),
        ),
    ]
