# Generated by Django 2.2.12 on 2020-06-28 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20200519_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Y', 'YouTube'), ('G', 'General')], default='G', max_length=1, verbose_name='Type of the Post Link')),
                ('display_text', models.TextField(blank=True, verbose_name='Display Text')),
                ('url', models.URLField(max_length=300, verbose_name='URL Link')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='community.Post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Post Lin',
                'verbose_name_plural': 'Post Link',
            },
        ),
    ]
