# Generated by Django 2.2.12 on 2020-06-28 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_postlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlink',
            options={'verbose_name': 'Post Link', 'verbose_name_plural': 'Post Links'},
        ),
    ]
