# Generated by Django 2.1.15 on 2020-04-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name of the City')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SL', 'Продажа'), ('PR', 'Приобретение'), ('RT', 'Аренда')], default='SL', max_length=2, verbose_name='Category of the Company')),
                ('title', models.CharField(max_length=100, verbose_name='Title of the Company')),
                ('product_description', models.TextField(verbose_name='Product Description')),
                ('company_description', models.TextField(verbose_name='Short Company Description')),
                ('phone_numbers', models.CharField(max_length=100, verbose_name='Phone Numbers')),
                ('emails', models.CharField(max_length=100, verbose_name='Emails')),
                ('web_sites', models.CharField(max_length=100, verbose_name='Websites')),
                ('instagram_url', models.CharField(max_length=100, verbose_name='Instagram')),
                ('facebook_url', models.CharField(max_length=100, verbose_name='Facebook')),
                ('cities', models.ManyToManyField(related_name='companies', to='catalog.City', verbose_name='Cities of the Company')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Title of the Direction')),
            ],
            options={
                'verbose_name': 'Direction of the Company',
                'verbose_name_plural': 'Directions of the Company',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='directions',
            field=models.ManyToManyField(related_name='companies', to='catalog.CompanyDirection', verbose_name='Directions of the Company'),
        ),
    ]
