# Generated by Django 2.1.15 on 2020-04-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200403_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='companyimages', verbose_name='Company Logo'),
        ),
    ]
