# Generated by Django 2.1.15 on 2020-05-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecalendar', '0003_auto_20200317_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breedingstockevent',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='calfevent',
            name='scheduled_date',
        ),
    ]
