# Generated by Django 2.1.15 on 2020-05-09 18:43

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecalendar', '0004_auto_20200509_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedingstockevent',
            name='scheduled_date_range',
            field=django.contrib.postgres.fields.ranges.DateRangeField(default=('2016-06-01', '2016-06-10'), verbose_name='Scheduled date range of the event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calfevent',
            name='scheduled_date_range',
            field=django.contrib.postgres.fields.ranges.DateRangeField(default=('2016-06-01', '2016-06-10'), verbose_name='Scheduled date range of the event'),
            preserve_default=False,
        ),
    ]
