# Generated by Django 2.1.15 on 2020-05-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecalendar', '0006_auto_20200510_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlebreedingstockevent',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of the event completion'),
        ),
        migrations.AlterField(
            model_name='singlecalfevent',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of the event completion'),
        ),
    ]
