# Generated by Django 2.1.15 on 2020-05-12 19:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecalendar', '0008_auto_20200511_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breedingstockevent',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='calfevent',
            name='attributes',
        ),
        migrations.AddField(
            model_name='singlebreedingstockevent',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlecalfevent',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
